# /bin/sh 
# ----------------Parameters---------------------- #
#$  -S /bin/sh
#$ -q sThM.q
#$ -l mres=16G,h_data=16G,h_vmem=16G,himem
#$ -cwd
#$ -j y
#$ -N hapi
#$ -o hapi.log
#
# ----------------Modules------------------------- #
module load intel/python/39-22.1
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
python main.py
#
echo = `date` job $JOB_NAME done
